language: cpp
compiler:
- gcc

branches:
  only:
  - master

sudo: false
dist: trusty

cache:
  directories:
  - $HOME/.hunter

script:
- mkdir build
- cd build
- cmake -DTREAT_WARNINGS_AS_ERRORS=ON ../
- make -k
- make fatest -k
after_success:
- cd ..
- ./update-gh-pages.sh
notifications:
  recipients:
  - wheybags+travis.ci@wheybags.com
  email:
    on_success: change
    on_failure: always
env:
  global:
    secure: b9143BbjFmQvaxruDHiUy1sW4InyZGejs4S/xgb4W1fFTzea9EMpzjWgwospBI3NPpe6xadctdypL9UbzJMXfD0PAZ39FbMIgl56pFkoZv1G9vwLOjG6ka0wXT7Pr6yP2FHkIdrQWECvvc1shTFXU9Yeystl0ISPwgphWUlwFZU=
